// frontend-svelte/src/components/output/HighlightedText.svelte
<script>
  import { getNextColor } from "../utils/helpers";

  export let value, theme;
  export let show_legend, color_map;
  color_map = color_map || {};
  let mode;

  if (value.length > 0) {
    for (let [_, label] of value) {
      if (label !== null) {
        if (typeof label === "string") {
          mode = "categories";
          if (!(label in color_map)) {
            let color = getNextColor(Object.keys(color_map).length);
            color_map[label] = color;
          }
        } else {
          mode = "scores";
        }
      }
    }
  }
  console.log(color_map);
</script>

<div class="output-highlightedtext" {theme}>
  {#if mode === "categories"}
    {#if show_legend}
      <div class="category-legend flex flex-wrap gap-1 mb-2">
        {#each color_map.entries() as [category, color], i}
          <div
            class="category-label px-2 py-1 rounded text-white font-semibold"
            style={"background-color" + color}
            key={i}
          >
            {category}
          </div>
        {/each}
      </div>
    {/if}
    <div
      class="textfield p-2 bg-white dark:bg-gray-800 rounded box-border max-w-full leading-8 break-word"
    >
      {#each value as [text, category], i}
        <span
          class="textspan p-1 mr-0.5 bg-opacity-20 dark:bg-opacity-80 rounded-sm"
          title={category}
          style={category === null
            ? ""
            : `color: ${color_map[category]}; background-color: ${color_map[
                category
              ].replace("1)", "var(--tw-bg-opacity))")}`}
          key={i}
        >
          <span class="text dark:text-white">{text}</span>
          {#if !show_legend && category !== null}
            <span
              class="inline-category text-xs text-white ml-0.5 px-0.5 rounded-sm"
              style={category === null
                ? ""
                : `background-color: ${color_map[category]}`}
            >
              {category}
            </span>
          {/if}
        </span>
      {/each}
    </div>
  {:else}
    {#if show_legend}
      <div
        class="color_legend flex px-2 py-1 justify-between rounded mb-3 font-semibold"
        style="background: -webkit-linear-gradient(to right,#8d83d6,(255,255,255,0),#eb4d4b); background: linear-gradient(to right,#8d83d6,rgba(255,255,255,0),#eb4d4b);"
      >
        <span>-1</span>
        <span>0</span>
        <span>+1</span>
      </div>
    {/if}
    <div
      class="textfield p-2 bg-white dark:bg-gray-800 rounded box-border max-w-full leading-8 break-word"
    >
      {#each value as [text, score], i}
        <span
          class="textspan p-1 mr-0.5 bg-opacity-20 dark:bg-opacity-80 rounded-sm"
          title={value}
          style={"background-color: rgba(" +
            (score < 0 ? "141, 131, 214," + -score : "235, 77, 75," + score) +
            ")"}
        >
          <span class="text dark:text-white">{text}</span>
        </span>
      {/each}
    </div>
  {/if}
</div>

<style lang="postcss">
  .output-highlightedtext[theme="default"] {
    .textfield {
      @apply shadow;
    }
  }
</style>

// frontend/src/components/output/highlighted_text.jsx
import React from "react";
import BaseComponent from "../base_component";
import ComponentExample from "../component_example";
import { getNextColor } from "../../utils";

class HighlightedTextOutput extends BaseComponent {
  constructor(props) {
    super(props);
    this.color_map = this.props.color_map || {};
    this.new_category_index = 0;
  }
  generate_category_legend(category_map) {
    for (let category in category_map) {
      if (category in this.color_map) {
        continue;
      }
      let color = category_map[category];
      if (!color) {
        color = getNextColor(this.new_category_index);
        this.new_category_index++;
      }
      this.color_map[category] = color;
    }
  }
  render() {
    if (this.props.value === null || this.props.value.length === 0) {
      return false;
    }
    let first_score = null;
    for (let span of this.props.value) {
      if (span[1] !== null) {
        first_score = span[1];
        break;
      }
    }
    if (typeof first_score === "string") {
      let new_color_map = {};
      for (let span of this.props.value) {
        let category = span[1];
        if (category != null) {
          new_color_map[category] = null;
        }
      }
      this.generate_category_legend(new_color_map);
      return (
        <div className="output_highlightedtext">
          {this.props.show_legend ? (
            <div className="category_legend">
              {Object.entries(this.color_map).map(([category, color]) => {
                return (
                  <div
                    className="category-label"
                    style={{ "background-color": color }}
                  >
                    {category}
                  </div>
                );
              })}
            </div>
          ) : (
            false
          )}
          <div className="textfield">
            {this.props.value.map((span) => {
              let category = span[1];
              let style = {};
              if (category !== null) {
                style["color"] = this.color_map[category];
                style["backgroundColor"] = style.color.replace(
                  "1)",
                  "var(--tw-bg-opacity))"
                );
              }
              return (
                <span class="textspan" title={category} style={style}>
                  <span class="text">{span[0]}</span>
                  {this.props.show_legend || span[1] === null ? (
                    false
                  ) : (
                    <span
                      class="inline_label"
                      style={{ backgroundColor: style.color }}
                    >
                      {span[1]}
                    </span>
                  )}
                </span>
              );
            })}
          </div>
        </div>
      );
    } else {
      return (
        <div className="output_highlightedtext">
          {this.props.show_legend ? (
            <div className="color_legend">
              <span>-1</span>
              <span>0</span>
              <span>+1</span>
            </div>
          ) : (
            false
          )}
          <div className="textfield">
            {this.props.value.map((span) => {
              let [text, value] = span;
              let color = "";
              if (value < 0) {
                color = "141, 131, 214," + -value;
              } else {
                color = "235, 77, 75," + value;
              }
              return (
                <span
                  class="textspan"
                  title={value}
                  style={{ backgroundColor: `rgba(${color})` }}
                >
                  <span class="text">{text}</span>
                </span>
              );
            })}
          </div>
        </div>
      );
    }
  }
}

class HighlightedTextOutputExample extends ComponentExample {
  render() {
    let output_string = "";
    for (const span of this.props.value) {
      output_string += span[0];
    }
    if (output_string.length > 20) {
      output_string = output_string.substring(0, 20) + "...";
    }
    return (
      <div className="output_highlighted_text_example">{output_string}</div>
    );
  }
}

export { HighlightedTextOutput, HighlightedTextOutputExample };
